package authz

import (
	"strings"
	"testing"
)

// Argon2id is what the PRD asks for and what a panel exposed to the internet
// needs: bcrypt's work factor is bounded by a 72-byte input and a cost that
// buys nothing against a GPU, while Argon2id's memory cost is the part an
// attacker cannot buy their way around cheaply.
func TestHashPassword_ProducesAnArgon2idPHCString(t *testing.T) {
	hash, err := HashPassword("correct horse battery staple")
	if err != nil {
		t.Fatalf("HashPassword: %v", err)
	}
	if !strings.HasPrefix(hash, "$argon2id$") {
		t.Errorf("hash = %q, want an argon2id PHC string", hash)
	}
	// The parameters travel with the hash, so raising them later still leaves
	// every existing password verifiable against the values it was made with.
	for _, want := range []string{"$v=19$", "m=", "t=", "p="} {
		if !strings.Contains(hash, want) {
			t.Errorf("hash %q does not record %q", hash, want)
		}
	}
}

func TestVerifyPassword_AcceptsTheRightOneAndRejectsTheRest(t *testing.T) {
	hash, err := HashPassword("correct horse battery staple")
	if err != nil {
		t.Fatalf("HashPassword: %v", err)
	}
	if !VerifyPassword(hash, "correct horse battery staple") {
		t.Error("the correct password was rejected")
	}
	for _, wrong := range []string{"", "Correct horse battery staple", "correct horse battery stapl", "correct horse battery staple "} {
		if VerifyPassword(hash, wrong) {
			t.Errorf("%q was accepted", wrong)
		}
	}
}

// Two users with the same password must not share a hash, or a leaked store
// tells an attacker which accounts to attack once rather than one at a time.
func TestHashPassword_SaltsEveryHash(t *testing.T) {
	first, err := HashPassword("same password")
	if err != nil {
		t.Fatalf("HashPassword: %v", err)
	}
	second, err := HashPassword("same password")
	if err != nil {
		t.Fatalf("HashPassword: %v", err)
	}
	if first == second {
		t.Fatal("the same password produced the same hash, so it is unsalted")
	}
	if !VerifyPassword(second, "same password") {
		t.Error("the second hash does not verify")
	}
}

// A hash servlo cannot parse is not a hash that matches everything. Every
// malformed form has to be a rejection, because the alternative is an
// authentication bypass reachable by corrupting one config field.
func TestVerifyPassword_RejectsEveryMalformedHash(t *testing.T) {
	valid, err := HashPassword("password")
	if err != nil {
		t.Fatalf("HashPassword: %v", err)
	}
	malformed := []string{
		"",
		"password",
		"$argon2id$",
		"$argon2id$v=19$m=65536,t=3,p=2$$",
		"$argon2id$v=19$m=65536,t=3,p=2$notbase64!!$notbase64!!",
		"$argon2i$v=19$m=65536,t=3,p=2$c2FsdHNhbHQ$aGFzaGhhc2g",
		"$bcrypt$whatever",
		"$argon2id$v=99$m=65536,t=3,p=2$c2FsdHNhbHQ$aGFzaGhhc2g",
		"$argon2id$v=19$m=0,t=0,p=0$c2FsdHNhbHQ$aGFzaGhhc2g",
		strings.TrimPrefix(valid, "$argon2id"),
	}
	for _, hash := range malformed {
		if VerifyPassword(hash, "password") {
			t.Errorf("malformed hash %q accepted a password", hash)
		}
		if VerifyPassword(hash, "") {
			t.Errorf("malformed hash %q accepted an empty password", hash)
		}
	}
}

// An empty stored hash is the state before anyone has set a password, and it
// must not be a state in which every password works.
func TestVerifyPassword_EmptyHashNeverMatches(t *testing.T) {
	if VerifyPassword("", "") || VerifyPassword("", "anything") {
		t.Error("an empty hash accepted a password")
	}
}

// bcrypt is what upstream stored. An install upgrading into this one still has
// those hashes and must keep being able to log in, or the upgrade locks the
// operator out of their own panel.
func TestVerifyPassword_StillAcceptsAnInheritedBcryptHash(t *testing.T) {
	// bcrypt cost 10 for "secret", generated by golang.org/x/crypto/bcrypt.
	const inherited = "$2a$10$PyYSdhGCPm5wN5NkhjEUReOq2pBb9xIUb8SpgGn1SeHta.xyb1A76"
	if !VerifyPassword(inherited, "secret") {
		t.Error("an inherited bcrypt hash no longer verifies, so an upgrade locks the operator out")
	}
	if VerifyPassword(inherited, "wrong") {
		t.Error("an inherited bcrypt hash accepted the wrong password")
	}
}

// A caller has to be able to tell that a stored hash is due for rehashing, or
// inherited bcrypt hashes stay bcrypt forever.
func TestNeedsRehash(t *testing.T) {
	fresh, err := HashPassword("password")
	if err != nil {
		t.Fatalf("HashPassword: %v", err)
	}
	if NeedsRehash(fresh) {
		t.Error("a hash made with the current parameters wants rehashing")
	}
	if !NeedsRehash("$2a$10$PyYSdhGCPm5wN5NkhjEUReOq2pBb9xIUb8SpgGn1SeHta.xyb1A76") {
		t.Error("an inherited bcrypt hash does not want rehashing")
	}
	if !NeedsRehash("$argon2id$v=19$m=1024,t=1,p=1$c2FsdHNhbHRzYWx0c2FsdA$aGFzaGhhc2hoYXNoaGFzaA") {
		t.Error("a hash made with weaker parameters does not want rehashing")
	}
}

// A password long enough to matter must not be silently truncated, which is
// exactly the bcrypt behaviour this replaces: two passphrases agreeing in
// their first 72 bytes hash identically there.
func TestHashPassword_DoesNotTruncateLongPassphrases(t *testing.T) {
	base := strings.Repeat("a", 72)
	hash, err := HashPassword(base + "first")
	if err != nil {
		t.Fatalf("HashPassword: %v", err)
	}
	if VerifyPassword(hash, base+"second") {
		t.Error("two passphrases differing only past 72 bytes verify against the same hash")
	}
	if !VerifyPassword(hash, base+"first") {
		t.Error("the long passphrase does not verify against its own hash")
	}
}
