package certs

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/ServloOfficial/servlo/internal/config"
)

// ReissueCert must hand the issuer the site's primary domain and every alias,
// so a domain mutation routed through it leaves no name the browser will
// reject. What SANs that implies is the issuer's business, not this layer's.
func TestReissueCert_coversEveryDomain(t *testing.T) {
	tmp := t.TempDir()
	t.Setenv("XDG_DATA_HOME", tmp)
	rec := withIssuer(t, &recordingIssuer{name: "test"})

	site := config.Site{
		Name:    "harborlist",
		Path:    filepath.Join(tmp, "project"),
		Domains: []string{"harborlist.example", "aaaddd.example"},
		Secured: true,
	}

	if err := ReissueCert(site); err != nil {
		t.Fatalf("ReissueCert: %v", err)
	}
	if len(rec.calls) != 1 {
		t.Fatalf("issuer called %d times, want 1", len(rec.calls))
	}
	if rec.calls[0].primary != "harborlist.example" {
		t.Errorf("primary = %q, want harborlist.example", rec.calls[0].primary)
	}
	if strings.Join(rec.calls[0].domains, ",") != "harborlist.example,aaaddd.example" {
		t.Errorf("issuer got domains %v, want the primary and every alias", rec.calls[0].domains)
	}
}

// RenewIfDue is the routine boot/watcher self-heal: it must leave a still-valid
// cert untouched so calling it every scan is cheap.
func TestRenewIfDue_reusesValidCert(t *testing.T) {
	tmp := t.TempDir()
	t.Setenv("XDG_DATA_HOME", tmp)
	rec := withIssuer(t, &recordingIssuer{name: "test"})

	certsDir := filepath.Join(tmp, "servlo", "certs", "sites")
	if err := os.MkdirAll(certsDir, 0755); err != nil {
		t.Fatal(err)
	}
	certPath := filepath.Join(certsDir, "myapp.example.crt")
	keyPath := filepath.Join(certsDir, "myapp.example.key")
	writeLeafCert(t, certPath, time.Now().Add(200*24*time.Hour))
	original, err := os.ReadFile(certPath)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(keyPath, []byte("KEY"), 0600); err != nil {
		t.Fatal(err)
	}

	site := config.Site{Name: "myapp", Path: filepath.Join(tmp, "myapp"), Domains: []string{"myapp.example"}, Secured: true}
	renewed, err := RenewIfDue(site)
	if err != nil {
		t.Fatalf("RenewIfDue: %v", err)
	}
	if renewed {
		t.Error("RenewIfDue reported a renewal of a still-valid cert, which would reload nginx for nothing")
	}
	if len(rec.calls) != 0 {
		t.Errorf("RenewIfDue called the issuer for a still-valid cert")
	}
	got, err := os.ReadFile(certPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != string(original) {
		t.Errorf("RenewIfDue reissued a still-valid cert; got %q want %q", got, original)
	}
}

// A cert inside the reissue window must be regenerated by RenewIfDue so a
// long-lived secured site self-heals before the leaf expires.
func TestRenewIfDue_reissuesAgingCert(t *testing.T) {
	tmp := t.TempDir()
	t.Setenv("XDG_DATA_HOME", tmp)
	rec := withIssuer(t, &recordingIssuer{name: "reissued"})

	certsDir := filepath.Join(tmp, "servlo", "certs", "sites")
	if err := os.MkdirAll(certsDir, 0755); err != nil {
		t.Fatal(err)
	}
	certPath := filepath.Join(certsDir, "myapp.example.crt")
	keyPath := filepath.Join(certsDir, "myapp.example.key")
	writeLeafCert(t, certPath, time.Now().Add(5*24*time.Hour))
	if err := os.WriteFile(keyPath, []byte("KEY"), 0600); err != nil {
		t.Fatal(err)
	}

	site := config.Site{Name: "myapp", Path: filepath.Join(tmp, "myapp"), Domains: []string{"myapp.example"}, Secured: true}
	renewed, err := RenewIfDue(site)
	if err != nil {
		t.Fatalf("RenewIfDue: %v", err)
	}
	if !renewed {
		t.Error("RenewIfDue reissued without saying so, so nothing would reload nginx onto the new certificate")
	}
	if len(rec.calls) != 1 {
		t.Fatalf("RenewIfDue did not reissue an aging cert; issuer called %d times", len(rec.calls))
	}
	got, err := os.ReadFile(certPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != "issued-by-reissued-cert" {
		t.Errorf("the aging cert was not replaced; body %q", got)
	}
}
