package certs

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/realrashid/servlo/internal/config"
)

// ReissueCert must cover the site's primary domain and every alias, so a
// domain mutation routed through it leaves no name the browser will reject.
func TestReissueCert_coversEveryDomain(t *testing.T) {
	tmp := t.TempDir()
	t.Setenv("XDG_DATA_HOME", tmp)

	binDir := filepath.Join(tmp, "servlo", "bin")
	if err := os.MkdirAll(binDir, 0755); err != nil {
		t.Fatal(err)
	}
	// Fake mkcert that echoes the SAN args into the cert so the test can
	// grep them. Matches the pattern used by manager_test.go.
	fakeMkcert := `#!/bin/sh
CRT=""
KEY=""
SANS=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    -cert-file) shift; CRT="$1" ;;
    -key-file)  shift; KEY="$1" ;;
    *) SANS="$SANS $1" ;;
  esac
  shift
done
printf '%s' "$SANS" > "$CRT"
printf 'KEY' > "$KEY"
`
	if err := os.WriteFile(filepath.Join(binDir, "mkcert"), []byte(fakeMkcert), 0755); err != nil {
		t.Fatal(err)
	}

	site := config.Site{
		Name:    "harborlist",
		Path:    filepath.Join(tmp, "project"),
		Domains: []string{"harborlist.test", "aaaddd.test"},
		Secured: true,
	}

	if err := ReissueCert(site); err != nil {
		t.Fatalf("ReissueCert: %v", err)
	}

	certPath := filepath.Join(tmp, "servlo", "certs", "sites", "harborlist.test.crt")
	body, err := os.ReadFile(certPath)
	if err != nil {
		t.Fatalf("reading cert: %v", err)
	}
	got := string(body)
	wantSANs := []string{
		"harborlist.test",
		"*.harborlist.test",
		"aaaddd.test",
		"*.aaaddd.test",
	}
	for _, san := range wantSANs {
		if !strings.Contains(got, san) {
			t.Errorf("SAN %q missing from cert; got %q", san, got)
		}
	}
}

func TestSecureSite_RefusesWhenDNSDisabled(t *testing.T) {
	tmp := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", tmp)
	t.Setenv("XDG_DATA_HOME", tmp)

	cfg := &config.GlobalConfig{}
	cfg.DNS.Enabled = false
	cfg.DNS.TLD = "localhost"
	if err := config.SaveGlobal(cfg); err != nil {
		t.Fatalf("SaveGlobal: %v", err)
	}

	site := config.Site{Name: "myapp", Domains: []string{"myapp.example"}}
	err := SecureSite(site)
	if !errors.Is(err, ErrDNSDisabled) {
		t.Fatalf("SecureSite err = %v, want ErrDNSDisabled", err)
	}
}

// EnsureCert is the routine boot/watcher self-heal: it must leave a still-valid
// cert untouched (no mkcert run) so calling it every scan is cheap.
func TestEnsureCert_reusesValidCert(t *testing.T) {
	tmp := t.TempDir()
	t.Setenv("XDG_DATA_HOME", tmp)
	fakeMkcertBin(t, tmp)

	certsDir := filepath.Join(tmp, "servlo", "certs", "sites")
	if err := os.MkdirAll(certsDir, 0755); err != nil {
		t.Fatal(err)
	}
	certPath := filepath.Join(certsDir, "myapp.test.crt")
	keyPath := filepath.Join(certsDir, "myapp.test.key")
	writeLeafCert(t, certPath, time.Now().Add(200*24*time.Hour))
	original, err := os.ReadFile(certPath)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(keyPath, []byte("KEY"), 0644); err != nil {
		t.Fatal(err)
	}

	site := config.Site{Name: "myapp", Path: filepath.Join(tmp, "myapp"), Domains: []string{"myapp.test"}, Secured: true}
	if err := EnsureCert(site); err != nil {
		t.Fatalf("EnsureCert: %v", err)
	}
	got, err := os.ReadFile(certPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != string(original) {
		t.Errorf("EnsureCert reissued a still-valid cert; got %q want %q", got, original)
	}
}

// A cert inside the reissue window must be regenerated by EnsureCert so a
// long-lived secured site self-heals before the leaf expires.
func TestEnsureCert_reissuesAgingCert(t *testing.T) {
	tmp := t.TempDir()
	t.Setenv("XDG_DATA_HOME", tmp)
	fakeMkcertBin(t, tmp)

	certsDir := filepath.Join(tmp, "servlo", "certs", "sites")
	if err := os.MkdirAll(certsDir, 0755); err != nil {
		t.Fatal(err)
	}
	certPath := filepath.Join(certsDir, "myapp.test.crt")
	keyPath := filepath.Join(certsDir, "myapp.test.key")
	writeLeafCert(t, certPath, time.Now().Add(5*24*time.Hour))
	if err := os.WriteFile(keyPath, []byte("KEY"), 0644); err != nil {
		t.Fatal(err)
	}

	site := config.Site{Name: "myapp", Path: filepath.Join(tmp, "myapp"), Domains: []string{"myapp.test"}, Secured: true}
	if err := EnsureCert(site); err != nil {
		t.Fatalf("EnsureCert: %v", err)
	}
	got, err := os.ReadFile(certPath)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "REISSUED") {
		t.Errorf("EnsureCert did not reissue an aging cert; body %q", got)
	}
	if !strings.Contains(string(got), "myapp.test") {
		t.Errorf("reissued cert missing SAN; body %q", got)
	}
}
